BUGFIX: Forgiving `I18nRegistry.translate` for strings with colons
The following node type configuration

```yaml
placeholder: 'ClientEval: node.properties.tagName'
```

currently yields an error which is caught by the error boundary for properties:

> Error: TranslationAddress must adhere to format "{packageKey}:{sourceName}:{transUnitId}". Got "ClientEval: node.properties.tagName" instead.

The newly added strictness in https://github.com/neos/neos-ui/pull/3804 introduces this regression here.

Previously the function `getTranslationAddress` would just attempt to spit a string and expect three items to be returned:

https://github.com/neos/neos-ui/blob/2cecfcf136aafcd9e3f72537f513eb81b01e993b/packages/neos-ui-i18n/src/registry/I18nRegistry.js#L7

The deconstruction would already cause an error in PHP but not in JavaScript:

```
const [packageKey, sourceName, id] = 'ClientEval: node.properties.tagName'.split(':')
```

Returns

```
packageKey: "ClientEval"
sourceName: " node.properties.tagName"
id: undefined
```

The previous forgiveness needs to be reintroduced as its easy to create errors with strings containing colons at any position which is definitely likely for placeholders. Imagine: `placeholder: "The title of the blog:"`.